### ISSUE TITLE
About next-term lecture

### ISSUE THREAD

**Issue by dfdu233** [guoquan/mountfs#2]
郭老师下学期不教课吗，教务系统没搜到

**Comment by guoquan** [comment]
Hi pal, I am subject to changes in my role and am not lecturing on the courses like last year. Sorry for not being able to share the classroom with you guys. Hope you still enjoy the class and your journey in AI.

Happy Hacking :octocat: 

---

Obviously this is an off-topic on this project, and I'd close it to make the thread clean.

**Comment by dfdu233** [comment]
I’m sorry to hear this news. You’re the best AI course instructor. Wishing you all the best!
